description: None

checkpoint: /project/home/p200177/DE_371/angeliquebonamy/anemoi/outputs_incond_x_0_probabilistic_low_noise/checkpoint/73f7278e180543469b320e3311bfff27/inference-last.ckpt
# checkpoint: /project/home/p200177/DE_371/avritj/experiments_anemoi/training/output/checkpoint/701613f37ab0461686b2135488d00289/inference-last.ckpt
# """A path to an Anemoi checkpoint file."""

runner:
  external_graph: 
    graph: /project/home/p200177/DE_371/avritj/graph_AROME_full.pt
# """The runner to use. For runners that take extra options, they can be passed here in dictionary format with the runner name as the top level dictionary key. For example, if using `parallel`, the `cluster` option can be set here."""

lead_time: 6
# """The lead time for the forecast. This can be a string, an integer or a timedelta object.
# If an integer, it represents a number of hours. Otherwise, it is parsed by :func:`anemoi.utils.dates.as_timedelta`.
# """
date: 2024-03-03
name: None
# """Used by prepml."""
# 
verbosity: 0
# """The verbosity level of the runner. This can be 0 (default), 1, 2 or 3."""

use_profiler: false
# """If True, the inference will be profiled, producing time and memory report."""

input: 
  dataset: /project/home/p200177/DE_371/datasets/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6/arome-an-oper-titan-0p025-2020-2024-1h-v4-eurw-precip6.zarr
# output: 
#   plot:
#     variables: ["10u", "10v", "2t"]
#     format: png
#     template: "plot_10steps_test_{date}.{format}"
#     dir: /project/home/p200177/DE_371/avritj/experiments_anemoi/inference/plots

output:
  netcdf:  /project/home/p200177/DE_371/avritj/experiments_anemoi/inference/netcdf_files/uncond_sample_lownoise.nc
pre_processors: []
post_processors: []
use_grib_paramid: False
write_initial_state: True
initial_state_categories: ["prognostics", "constant_forcings"]
env: {}
patch_metadata: {}
development_hacks: {}
debugging_info: {}
preload_checkpoint: False
# noise_scheduler_params : 
#   schedule_type: "karras"
#   sigma_max: 100.0
#   sigma_min: 0.02
#   rho: 7.0
#   num_steps: 50
#   num_steps_sdedit: 23
#   SDEdit: False
        