description: None

checkpoint: /project/home/p200177/DE_371/avritj/anemoi/training/Training_complet_mean_finetuning_2/checkpoint/eea90a5b6e38478cbface1776630944a/inference-last.ckpt


runner:
  sdedit_scoring:
    noise_scheduler_params:
      schedule_type: "karras"
      sigma_max: 1000
      sigma_min: 0.02
      rho: 7.0
      num_steps: 100 
      num_steps_sdedit: 12 # number of steps
      SDEdit: True # Activate SDEdit method 
    sampler_params:
      sampler: "heun"
      S_churn: 2.5
      S_min: 0.75
      S_max: 1000
      S_noise: 1.05
    condition_files:
      mean_point: "/project/home/p200177/DE_371/avritj/mean_train_vars_no_tp.npy"
      mean_vars: "/project/home/p200177/DE_371/avritj/mean.npy"
      std_vars: "/project/home/p200177/DE_371/avritj/stdev.npy"

lead_time: 9

date: 2024-09-30T18:00:00

input: 

  dataset: /project/home/p200177/DE_371/datasets/arome-an-oper-titan-0p025-2024-2024-1h-v5-eurw-precip-6-october.zarr

output: 
  tee:
  - grib:
      post_processors:
        - backward_transform_filter:
              filter: fill_square
              fill_value: 9999
              max_lon_output: 16.0
              min_lon_output: -12.0
              max_lat_output: 55.4
              min_lat_output: 37.5
      path: /project/home/p200177/DE_371/avritj/experiments_anemoi/inference/grib/not_processed/SDEdit_{date}_test.grib
      templates:
        file: /project/home/p200177/DE_371/resources/AROME_IA/template.grib
      write_initial_state: false
  - netcdf:  
      path: /project/home/p200177/DE_371/avritj/experiments_anemoi/inference/grib/not_processed/SDEdit_{date}_test.nc # <- c'est ça qu'on change dans le slurm
      write_initial_state: true
 
initial_state_categories: ["prognostics", "constant_forcings"]
